# Generated by Django 5.1.7 on 2025-04-14 13:52

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='BD')),
                ('appointment_date', models.DateTimeField()),
                ('registration', models.CharField(max_length=100)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mechanic')),
            ],
        ),
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
